version: "3"

services:

  runtime-setup:
    image: swift-service-discovery:16.04-5.3
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.3"

  test:
    image: swift-service-discovery:16.04-5.3
    environment:
      - SANITIZER_ARG=--sanitize=thread
    command: /bin/bash -xcl "swift test --enable-test-discovery -Xswiftc -warnings-as-errors $${SANITIZER_ARG-}"

  shell:
    image: swift-service-discovery:16.04-5.3
