version: "3"

services:

  runtime-setup:
    image: swift-service-discovery:20.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-focal"
        
  build:
    image: swift-service-discovery:20.04-main
    environment: []
      #- SANITIZER_ARG=--sanitize=thread
    command: /bin/bash -xcl "swift build -Xswiftc -warnings-as-errors $${SANITIZER_ARG-} -Xswiftc -Xfrontend -Xswiftc -enable-experimental-concurrency"

  test:
    image: swift-service-discovery:20.04-main
    environment: []
      #- SANITIZER_ARG=--sanitize=thread
    command: /bin/bash -xcl "swift test --enable-test-discovery -Xswiftc -warnings-as-errors $${SANITIZER_ARG-} -Xswiftc -Xfrontend -Xswiftc -enable-experimental-concurrency"

  shell:
    image: swift-service-discovery:20.04-main
